// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(BikeContext))]
    [Migration("20240107202433_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Data.Bike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfUnitsNeed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Bikes");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Bike");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WebApi.Data.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComponentId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("WheelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WheelId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("WebApi.Data.Break", b =>
                {
                    b.HasBaseType("WebApi.Data.Bike");

                    b.HasDiscriminator().HasValue("Break");
                });

            modelBuilder.Entity("WebApi.Data.Pedal", b =>
                {
                    b.HasBaseType("WebApi.Data.Bike");

                    b.HasDiscriminator().HasValue("Pedal");
                });

            modelBuilder.Entity("WebApi.Data.Seat", b =>
                {
                    b.HasBaseType("WebApi.Data.Bike");

                    b.HasDiscriminator().HasValue("Seat");
                });

            modelBuilder.Entity("WebApi.Data.Wheel", b =>
                {
                    b.HasBaseType("WebApi.Data.Bike");

                    b.Property<int>("Frames")
                        .HasColumnType("int");

                    b.Property<int>("Tubes")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Wheel");
                });

            modelBuilder.Entity("WebApi.Data.Stock", b =>
                {
                    b.HasOne("WebApi.Data.Wheel", null)
                        .WithMany("Stocks")
                        .HasForeignKey("WheelId");
                });

            modelBuilder.Entity("WebApi.Data.Wheel", b =>
                {
                    b.Navigation("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
